/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-11-30 08:33:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>首页</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"client/css/main.css\" type=\"text/css\"/>\n");
      out.write("<link type=\"text/css\" href=\"css/autoplay.css\" rel=\"stylesheet\" />\n");
      out.write("</head>\n");
      out.write("<body calss=\"main\">\n");
      out.write("<!-- 1.网页顶部start -->\n");
      out.write("<div id=\"dibhead\">\n");
      out.write("<table cellspaceing=\"0\" calss=\"headtable\">\n");
      out.write("<tr>\n");
      out.write("<td>\n");
      out.write("<a href=\"#\"><img alt=\"小猪佩奇\" src=\"client/images/logo.jpg\" width=\"200\" height=\"60\" border=\"0\" /></a>\n");
      out.write("</td>\n");
      out.write("<td style=\"text-align:right\">\n");
      out.write("<img alt=\"购物车\" src=\"client/images/cart.png\" width=\"26\" height=\"23\" style=\"margin-bottom:-4px\" />&nbsp;<a href=\"#\">我的账户</a>\n");
      out.write("| <a href=\"#\">帮助中心</a>\n");
      out.write("| <a href=\"#\">注销</a>\n");
      out.write("| <a href=\"register.html\">新用户注册</a>\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("</div>\n");
      out.write("<!-- 网页顶部结束 -->\n");
      out.write("<!-- 网页菜单列表 -->\n");
      out.write("<div id=\"divmenu\">\n");
      out.write("<a href=\"#\">查询</a>\n");
      out.write("<a href=\"#\">借阅</a>\n");
      out.write("<a href=\"#\" style=\"color:#FFFF00\">全部图书目录</a>\n");
      out.write("</div>\n");
      out.write("<div id=\"divsearch\">\n");
      out.write("<form action=\"#\" id=\"searchform\">\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\">\n");
      out.write("<tr>\n");
      out.write("<td style=\"text-align:right;padding-right:220px\">\n");
      out.write("Search\n");
      out.write("<input type=\"text\" name=\"textfield\" class=\"inputtable\" id=\"textfield\" value=\"请输入书名\" onmouserover=\"this.foocus();\"\n");
      out.write("onclick=\"my_click(this,'textfield');\" onBlur=\"my_blur(this,'textfield');\" />\n");
      out.write("<a href=\"#\">\n");
      out.write("<img alt=\"搜素\" src=\"client/images/serchbutton.png\" border=\"0\" style=\"margin-bottom:-4px\" onclick=\"search()\" />\n");
      out.write("</a>\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("</form>\n");
      out.write("</div>\n");
      out.write("<!-- 网页首页轮播图 -->\n");
      out.write("<div id=\"box_autoplay\">\n");
      out.write("<div class=\"list\">\n");
      out.write("<ul>\n");
      out.write("<li><img alt=\"\" src=\"client/ad/031019cdba1a91dc2d324f67c82b83a7.jpg\" width=\"1000\" height=\"335\" /></li>\n");
      out.write("<li><img alt=\"\" src=\"client/ad/3dcf85d67fbbdc29418ac0bc0e9de1fd.jpg\" width=\"1000\" height=\"335\" /></li>\n");
      out.write("<li><img alt=\"\" src=\"client/ad/62e74d09a526f5250c3c16f5bbb7d342.jpg\" width=\"1000\" height=\"335\" /></li>\n");
      out.write("<li><img alt=\"\" src=\"client/ad/7941f6a91755e0fb5d65e82e30e8a0ca.jpg\" width=\"1000\" height=\"335\" /></li>\n");
      out.write("<li><img alt=\"\" src=\"client/ad/f659a9f0e0bface85c180eff15d27094.jpg\" width=\"1000\" height=\"335\" /></li>\n");
      out.write("<script>\n");
      out.write("            window.onload = function(){\n");
      out.write("\n");
      out.write("                var images = document.getElementsByTagName('li');\n");
      out.write("                var pos = 0;\n");
      out.write("                var len = images.length;\n");
      out.write("\n");
      out.write("                setInterval(function(){\n");
      out.write("\n");
      out.write("                    images[pos].style.display = 'none';\n");
      out.write("                    pos = ++pos == len ? 0 : pos;\n");
      out.write("                    images[pos].style.display = 'inline';\n");
      out.write("\n");
      out.write("                },1000);\n");
      out.write("\n");
      out.write("            };\n");
      out.write("        </script>\n");
      out.write("</ul>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<!-- 公告栏 -->\n");
      out.write("<div id=\"divcontent\">\n");
      out.write("<table width=\"900px\" border=\"0\" cellspacing=\"0\">\n");
      out.write("<tr>\n");
      out.write("<td width=\"497\">\n");
      out.write("<img alt=\"\" src=\"client/images/announcement_457px_1153631_easyicon.net.png\" width=\"497\" height=\"38\" />\n");
      out.write("<table cellspacing=\"0\" class=\"ctl\">\n");
      out.write("<tr>\n");
      out.write("<td width=\"485\" height=\"29\">啦啦啦啦啦啦啦啦啦啦啦啦啦啦啦啦</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("</td>\n");
      out.write("<td style=\"padding:5px 15px 10px 40px\">\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\">\n");
      out.write("<tr>\n");
      out.write("<td>\n");
      out.write("<img alt=\"\" src=\"client/images/logo.jpg\" width=\"126\" height=\"29\" />\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\">\n");
      out.write("<tr>\n");
      out.write("<td style=\"width:80;text-align:center\">\n");
      out.write("<a href=\"#\">\n");
      out.write("<img alt=\"\" src=\"client/images/logo.jpg\" width=\"102\" height=\"130\" border=\"0\" />\n");
      out.write("</a>\n");
      out.write("<br />\n");
      out.write("</td>\n");
      out.write("<td style=\"width:80;text-align:center\">\n");
      out.write("<a href=\"#\">\n");
      out.write("<img alt=\"\" src=\"client/images/logo.jpg\" width=\"102\" height=\"130\" border=\"0\" />\n");
      out.write("</a>\n");
      out.write("<br />\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("</div>\n");
      out.write("<!-- 网页底部 -->\n");
      out.write("<div id=\"divfoot\">\n");
      out.write("<table width=\"100%\" border=\"0\">\n");
      out.write("<tr>\n");
      out.write("<td rowspan=\"2\" style=\"width:10%\">\n");
      out.write("<img alt=\"\" src=\"client/images/logo.jpg\" width=\"195\" height=\"50\" style=\"margin-left:175px\" />\n");
      out.write("</td>\n");
      out.write("<td style=\"padding-top:5px;padding-left:50px\">\n");
      out.write("<a href=\"#\">\n");
      out.write("<font color=\"#747556\"><b>CONTACT US</b></font>\n");
      out.write("</a>\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td style=\"padding-left:50px\">\n");
      out.write("<font color=\"#CCCCCC\">\n");
      out.write("<b>COPYRIGHT 2018 &copy;BookStore All.</b>\n");
      out.write("</font>\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
